language: python
sudo: false
python:
  - 2.7
  - 3.4
before_install:
  - pip install Sphinx Werkzeug alabaster invoke
install:
  - pip install .
script:
  - make test
deploy:
  - git clean -f
  - git config --global user.name "Ahmet Bakan"
  - git config --global user.email "lordnapi@gmail.com"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=ABLOG_KEY -m="`git log -1 --pretty=%B`"
  - git checkout --orphan gh-pages
  - rm $(git ls-files)
  - git rm --cached $(git ls-files)
  - git add .
  - git commit
  - git push origin gh-pages
