language: python
python:
  - 2.7
  - 3.4
before_install:
  - pip install Sphinx Werkzeug alabaster
install:
  - pip install .
script:
  - cd docs; ablog build -T
  - printf "\nABlog\nABlog Team\nhttp://ablog.readthedocs.org\n\nGA" | ablog start