language: python
sudo: false
python:
  - 2.7
  - 3.4
before_install:
  - pip install Sphinx Werkzeug alabaster invoke
install:
  - pip install .
script:
  - make test
deploy:
  _ git checkout --orphan gh-pages
  _ rm $(git ls-files)
  _ git rm --cached $(git ls-files)
  _ git add .
  _ git commit
  _ git push origin gh-pages
