apt-run: &apt-install
  name: Install apt packages
  command: |
    apt update
    apt install -y graphviz build-essential pandoc

docs-install: &docs-install
  name: Install Python dependencies
  command: |
    pip install werkzeug sphinx alabaster invoke python-dateutil sphinx-automodapi nbsphinx ipython

version: 2
jobs:

  egg-info-27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: python setup.py egg_info

  egg-info-35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python setup.py egg_info

  egg-info-36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python setup.py egg_info

  egg-info-37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python setup.py egg_info

  html-docs:
    docker:
      - image: continuumio/miniconda3
    steps:

      - checkout
      - run: *apt-install
      - run: *docs-install
      - run: python setup.py build_sphinx
      - store_artifacts:
          path: build/sphinx/html/index.html

      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/build/sphinx/html/index.html"; echo $DOCS_URL

workflows:
  version: 2

  egg-info:
    jobs:
      - egg-info-27
      - egg-info-35
      - egg-info-36
      - egg-info-37

  documentation:
    jobs:
      - html-docs


notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
