name: Docs
on:
  push:
    branches: [ablog_with_furo]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ablog_with_furo
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz pandoc
          pip install --upgrade pip
          pip install .[docs,notebook,markdown]
          pip install tox ghp-import

      - name: Build docs
        run: |
          pushd docs
          sphinx-build -j auto --color --keep-going -b html -d _build/.doctrees . _build/html 
          popd

      - name: Run ghp-import
        run: |
          git config user.name ABD-01
          git config user.email 63636498+ABD-01@users.noreply.github.com
          ghp-import -n -p -f -o docs/_build/html